/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppReceiptsRouteImport } from './routes/_app.receipts'
import { Route as AppLoansRouteImport } from './routes/_app.loans'
import { Route as AppInvestmentsRouteImport } from './routes/_app.investments'
import { Route as AppFaqRouteImport } from './routes/_app.faq'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCashflowRouteImport } from './routes/_app.cashflow'
import { Route as AppAccountsRouteImport } from './routes/_app.accounts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReceiptsRoute = AppReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansRoute = AppLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentsRoute = AppInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AppRoute,
} as any)
const AppFaqRoute = AppFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCashflowRoute = AppCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AppAccountsRoute
  '/cashflow': typeof AppCashflowRoute
  '/dashboard': typeof AppDashboardRoute
  '/faq': typeof AppFaqRoute
  '/investments': typeof AppInvestmentsRoute
  '/loans': typeof AppLoansRoute
  '/receipts': typeof AppReceiptsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AppAccountsRoute
  '/cashflow': typeof AppCashflowRoute
  '/dashboard': typeof AppDashboardRoute
  '/faq': typeof AppFaqRoute
  '/investments': typeof AppInvestmentsRoute
  '/loans': typeof AppLoansRoute
  '/receipts': typeof AppReceiptsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/cashflow': typeof AppCashflowRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/faq': typeof AppFaqRoute
  '/_app/investments': typeof AppInvestmentsRoute
  '/_app/loans': typeof AppLoansRoute
  '/_app/receipts': typeof AppReceiptsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounts'
    | '/cashflow'
    | '/dashboard'
    | '/faq'
    | '/investments'
    | '/loans'
    | '/receipts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/accounts'
    | '/cashflow'
    | '/dashboard'
    | '/faq'
    | '/investments'
    | '/loans'
    | '/receipts'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/accounts'
    | '/_app/cashflow'
    | '/_app/dashboard'
    | '/_app/faq'
    | '/_app/investments'
    | '/_app/loans'
    | '/_app/receipts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/receipts': {
      id: '/_app/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AppReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans': {
      id: '/_app/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AppLoansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investments': {
      id: '/_app/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AppInvestmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faq': {
      id: '/_app/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof AppFaqRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cashflow': {
      id: '/_app/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof AppCashflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppCashflowRoute: typeof AppCashflowRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFaqRoute: typeof AppFaqRoute
  AppInvestmentsRoute: typeof AppInvestmentsRoute
  AppLoansRoute: typeof AppLoansRoute
  AppReceiptsRoute: typeof AppReceiptsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppCashflowRoute: AppCashflowRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFaqRoute: AppFaqRoute,
  AppInvestmentsRoute: AppInvestmentsRoute,
  AppLoansRoute: AppLoansRoute,
  AppReceiptsRoute: AppReceiptsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
